### ISSUE TITLE
I get 'Cannot find a test server'

### ISSUE THREAD

**Issue by omriravid** [fopina/pyspeedtest#15]
Hi,

My code is:
`
st = pyspeedtest.SpeedTest()
    try:
        ping = st.ping()
        download = st.download()
        upload = st.upload()
    except Exception as e:
        logger.warning(f'speed test failure. {e}')
`
I get 'Cannot find a test server'
Sometimes it works, sometimes it doesn't. Lately it just doesn't..

Any idea why?
Thanks!

**Comment by jmfer1** [comment]
I have the same problem, can you please advise?

**Comment by nullberg** [comment]
I have the same problem as well: 'Cannot find a test server'

**Comment by 1010Manoj** [comment]
my guess is: This project probably violates SpeedTest.net's terms of service, so they blocked it. The author tried to get around the block, they blocked it again, and the author gave up. In the intervening two years, any other servers it used as backups either blocked it, or shut down (e.g., speedtest.serv.pt, mentioned in the docs, no longer exists).

**Comment by fopina** [comment]
Hey, I haven’t had much time to maintain this lately. I assume the project is not big enough per se to be blocked by them though there might be a lot of utilities doing things in a similar way and that “way” is being blocked or deprecated due to their new html5 app which might use a different setup (haven’t looked into it).

I do have this to review in my personal roadmap but without a due date :) plus a few other details (like proper docs).

If anyone finds anything, PRs are always welcome (though a bit delayed on review as well)

**Comment by bera5186** [comment]
@nullberg refer to this https://stackoverflow.com/questions/50999879/pyspeedtest-cannot-find-test-server

**Comment by 1010Manoj** [comment]
Are you sure this is working?

Thanks and Regards,
Manoj Lamkhade
+91 9665896220

**Comment by bera5186** [comment]
@1010Manoj  yep its working !!!

**Comment by PeterSR** [comment]
Had the same issue and changing 

```python
186:        connection = self.connect('www.speedtest.net')
```
to 
```python
186:        connection = self.connect('c.speedtest.net')
```
also solved it for me.

One way to future-proof this would be allow the class to take an optional argument with the url to the server.

**Comment by GrexAut** [comment]
`pyspeedtest -s c.speedtest.net`
is also working.

Thanks!

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
