### ISSUE TITLE
Upload() Error

### ISSUE THREAD

**Issue by ghost** [fopina/pyspeedtest#19]
Hey,

I am currently using pyspeedtest to write a very simple internet speed tester, below is my code...

`import pyspeedtest

#Enter your test server URL
test_server = ("c.speedtest.net")
tester = pyspeedtest.SpeedTest(test_server)
download = tester.download()
#upload = tester.upload()
ping = tester.ping()

#Converts the Float to Int
d = int(download)
#u = int(upload)
p = int(ping)

#Prints the results
print("You are using server -", test_server)
print("\nYour Results are...\n")
print("Download Speed is -", d, "Mbps")
#print("Your Up Speed is - ", u, "Mbps")
print("Ping is -", p, "ms")`

I have commented out the upload part of the code as this does not seem to work, i get the below error...

Traceback (most recent call last):
  File "/Users/grantpeach/Desktop/Internet Speed Checker.py", line 7, in <module>
    upload = tester.upload()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyspeedtest.py", line 150, in upload
    thread.run_number, thread.uploaded)
AttributeError: 'Thread' object has no attribute 'uploaded'

Any ideas?

Thanks

**Comment by AnselmC** [comment]
Hey,

I had the same issue.
The problem ist that speedtest.net's api has changed and pyspeedtest has been inactive for several years. 
The actual error happens before the traceback you posted:
`ValueError: invalid literal for int() with base 10: '"http://www.w3.org/1999/xhtml" xml:lang'`
This is because the GET request performed in pyspeedtest returns a 404 and this results in a parsing error (you can check this with `pyspeedtest -s 'c.speedtest.net' -d 2`).
Ping and download are not affected by this because ping just calculates the response time of the 404 and download the size of the 404 page. You can verify this by checking the code.

I don't think it makes sense to hack a solution (especially if you want to distribute your project). I haven't tried yet, but maybe speedtest-cli works better (https://github.com/sivel/speedtest-cli/).

Cheers

**Comment by ghost** [comment]
I see, I agree no point trying to sort it! I will look into speedtest-cli thanks 👍

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
